stages:
  # - mirror
  - build
  - deploy

variables:
  RUST_VERSION: stable

# mirror:
#   stage: mirror
#   script:
#     - git clone --mirror https://gitlab.com/saliaku/pooi-kailas.git mirror_repo
#     - cd mirror_repo
#     - git remote set-url --push origin git@github.com:saliaku/pooi-kailas.git
#     - git fetch -p origin
#     - git push --mirror origin
#   only:
#     - main  # or specific branches you want to mirror


build:
  stage: build
  image: "rust:latest"
  before_script:
    - apt-get update && apt-get install -y cmake  # For Debian/Ubuntu based images
    # Uncomment the following line for CentOS/RHEL based images
    #- yum install -y cmake
  script:
    - cargo install cargo-deb
    - cargo build --release
    - cargo-deb
  artifacts:
    paths:
      - target/debian/*.deb

deploy:
  stage: deploy
  script:
    - git archive --format=tar.gz -o pooi-$CI_COMMIT_REF_NAME.tar.gz HEAD
  artifacts:
    paths:
      - pooi-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags


