image: "rust:latest"
stages:
  - build
  - deploy

variables:
  RUST_VERSION: stable

build:
  stage: build
  script:
    - rustup default $RUST_VERSION
    - cargo build --release

deploy:
  stage: deploy
  script:
    - rustup default $RUST_VERSION
    - cargo build --release
    - echo "Deploy your release here"  # Add deployment steps
    - tar czf pooi-$CI_COMMIT_REF_NAME.tar.gz target/release/pooi
  only:
    - tags
