stages:
  - build
  - deploy

variables:
  RUST_VERSION: stable

build:
  stage: build
  image: "rust:latest"
  before_script:
    - apt-get update && apt-get install -y cmake  # For Debian/Ubuntu based images
    # Uncomment the following line for CentOS/RHEL based images
    #- yum install -y cmake
  script:
    - cargo install cargo-deb
    - cargo build --release
    - cargo-deb
  artifacts:
    paths:
      - target/debian/*.deb

deploy:
  stage: deploy
  script:
    - git archive --format=tar.gz -o pooi-$CI_COMMIT_REF_NAME.tar.gz HEAD
  artifacts:
    paths:
      - pooi-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags
