
stages:
  - build
  - deploy

variables:
  RUST_VERSION: stable

build:
  stage: build
  image: "rust:latest"
  script:
    - cargo install cargo-deb
    - cargo build --release
    - cargo-deb
  artifacts:
    paths:
      - target/debian/*.deb


deploy:
  stage: deploy
  script:
    - git archive --format=tar.gz -o pooi-$CI_COMMIT_REF_NAME.tar.gz HEAD
  artifacts:
    paths:
      - pooi-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags
