image: "rust:latest"
stages:
  - build
  - deploy

variables:
  RUST_VERSION: stable

build:
  stage: build
  script:
    - rustup default $RUST_VERSION
    - cargo version

deploy:
  stage: deploy
  script:
    - git archive --format=tar.gz -o pooi-$CI_COMMIT_REF_NAME.tar.gz HEAD
  artifacts:
    paths:
      - pooi-$CI_COMMIT_REF_NAME.tar.gz
  only:
    - tags
